# Generated by Django 4.1.3 on 2022-12-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_follow_followed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='follower',
            field=models.ManyToManyField(blank=True, to='app.follow'),
        ),
    ]
