# Generated by Django 4.1.3 on 2022-12-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_follower_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='follower',
        ),
    ]
