# Generated by Django 4.1.3 on 2022-12-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-updated', '-created')},
        ),
    ]
