# Generated by Django 4.1.3 on 2022-12-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_view',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
