# Generated by Django 4.1.3 on 2023-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_post_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
